### ISSUE TITLE
Action bars to only allow left-click.

### ISSUE THREAD

**Issue by dailytabs** [tukui-org/ElvUI#1089]
**Is your feature request related to a problem? Please describe.**
I have mouse thumb buttons assigned to action bars. When I hover over any action bar button and press a thumb button, instead of the assigned action being performed, the currently hovered over button is activated.

**Describe the solution you'd like**
I do not use any crazy macros with button alternatives and would like an option to only allow left-clicks to activate the action bar buttons.

**Comment by dailytabs** [comment]
Obviously, if self-cast right-click is activated, that would work as well ;)

**Comment by kodewdle** [comment]
self-cast right-click only isn't something that is supported by the API, you can register only left/right/middle up/down or any up/down however either of these would require modifying the action button lib so i'm going to close this as it's a quite more advanced thing to request and keydown is currently not worker great anyways because of Evokers
