### ISSUE TITLE
Abandoning wrong quest.

### ISSUE THREAD

**Issue by dailytabs** [tukui-org/ElvUI#1090]
### What is the issue you are having?

Abandoning pops up a message for a quest that I am not on extremely often. When not paying attention, I accept and abandon the wrong quest.

### What is the expected behavior?

Selected quest should be abandoned.

### What actually happened?

Pop up lists a different quest.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by dailytabs** [comment]
Only happens from the ElvUI quest log - never from objectives list.

Blizz doesn't even list a message for the abandoned quest, so you are SoL on getting it back.

**Comment by fisle** [comment]
Seems to be caused by the experience databar which is looping thru all the quests in the log and selecting them to gather quest reward XP. I'm not sure if the `SelectQuestLogEntry` function call is even needed, but one fix would be to save the initial quest to a variable before starting the loop, and restoring it after.

https://github.com/tukui-org/ElvUI/blob/development/ElvUI/Core/Modules/DataBars/Experience.lua#L42

**Comment by Azilroka** [comment]
It is needed. It would be nice if we didn't have to select it.
