### ISSUE TITLE
[Feature Request] Possibilty to split bags datatext free and reagents

### ISSUE THREAD

**Issue by Dabbel** [tukui-org/ElvUI#1097]
**Is your feature request related to a problem? Please describe.**
The bags datatext can display the total free space including the free space from reagents. This isn't very helpful. If i have 0 normal free bag slots and 6 free reagent slots the datatext shows 6 free slots but that isn't actual true.

**Describe the solution you'd like**
More text formats for the bag customization that splits up the free and free reagent slots.

**Comment by kodewdle** [comment]
added Include Reagents option, it will just change what is display on the Datatext itself but the tooltip will include all still

**Comment by Dabbel** [comment]
Hello kodewdle,

i thought more about text formats like 'Free/Reagent Free/Total' and 'Free/Reagent Free'.

That the tooltip isn't change is for me absolute fine.

**Comment by Dabbel** [comment]
@kodewdle the change broke the existing text formats, they are now missing
![image](https://github.com/tukui-org/ElvUI/assets/4102052/fc9b0b74-ce09-4574-a979-8db38b1a7866)

**Comment by kodewdle** [comment]
whoops, accident because we didn't have those listed in abc order
i adjusted it more in dev:
![image](https://github.com/tukui-org/ElvUI/assets/2266754/5ab44b25-2a36-40ec-b9a1-1aad21f4de27)
for example free/total with include would show as
![image](https://github.com/tukui-org/ElvUI/assets/2266754/1848e3d7-c25d-4716-b3d4-32995ea85581)
and without as 
![image](https://github.com/tukui-org/ElvUI/assets/2266754/943e7d8c-9643-49e9-b181-8e20e9913cce)
