### ISSUE TITLE
Enchants don't show in character info or inspect

### ISSUE THREAD

**Issue by collinstevens** [tukui-org/ElvUI#1231]
### Troubleshooting Steps

![image](https://github.com/tukui-org/ElvUI/assets/19230602/21caff92-cb1e-4f0c-a503-cae5b9798bd9)
![image](https://github.com/tukui-org/ElvUI/assets/19230602/daecf7b6-8de0-40eb-9ee7-5c08bbf7bea6)

### Describe the expected behavior and what actually happened?

The item level, gems, and rarity of each item in `Character Info` and `Inspect` are displaying, but the **enchants** aren't displaying.

The tooltip for `Display Inspect Info` is `Shows item level of each item, enchants, and gems when inspecting another player.`
The tooltip for `Display Character Info` is `Shows item level of each item, enchants, and gems on the character page.`.

### Reproducing the issue.

1. Enable `Display Inspect Info` and `Display Character Info` in `General` > `BlizzUI Improvements` > `Item Level`.
2. Open `Character Info` or `Inspect` on another player.

### Lua Errors

```shell
N/A
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Repooc** [comment]
Correct, they do not show due to how wow displays them in the tooltip. The only thing you can get regarding enchants on an item, is an enchant id from the item link, but wow has no api to use that id to get the actual enchant text. In retail we scan the tooltip to get the enchant as the enchants are prefixed in the tooltip with `Enchanted:`, that is not the case in cata... so no enchant will show... since we do not plan on maintaining a database with enchants and their enchantid which is the only reliable way to display the enchant string in cata.

I have a plugin that I am in middle of reworking but has a working alpha version on curseforge and wago addons named cataarmory that can display the enchant info since I have a list of enchants and the enchant ids...

**Comment by collinstevens** [comment]
> Correct, they do not show due to how wow displays them in the tooltip. The only thing you can get regarding enchants on an item, is an enchant id from the item link, but wow has no api to use that id to get the actual enchant text. In retail we scan the tooltip to get the enchant as the enchants are prefixed in the tooltip with `Enchanted:`, that is not the case in cata... so no enchant will show... since we do not plan on maintaining a database with enchants and their enchantid which is the only reliable way to display the enchant string in cata.
> 
> I have a plugin that I am in middle of reworking but has a working alpha version on curseforge and wago addons named cataarmory that can display the enchant info since I have a list of enchants and the enchant ids...

Ok, I'll check out your addon.

I was using BetterCharacterPanel as a substitute and it looks like they are just doing some checking on the enchant text for how they display it.
