### ISSUE TITLE
Problem when switching specs

### ISSUE THREAD

**Issue by coalgiver** [tukui-org/ElvUI#1317]
### Troubleshooting Steps

I play as an evoker.  When switching specs from devastation and then to preservation, I am noticing that my macro/spell positions on the action bars are not saving and staying in the desired position.

[Screenshot 2024-08-23 163805.zip](https://github.com/user-attachments/files/16733847/Screenshot.2024-08-23.163805.zip)

Screenshot will show the status and the missing spells on the action bar being blank.

### Describe the expected behavior and what actually happened?

I play as an evoker.  When switching specs from devastation and then to preservation, I am noticing that my macro/spell positions on the action bars are not saving and staying in the desired position.  However, what does happen is the difference in macro/spell position gets completed removed (blank action button on action bar).  Is there way to have this fixed?  I have tried to do the /edebug on command and the problem still exists.  Also, the problem is happening with the default UI of elvui.  If use the games (blizzard's) default UI, the problem does not exist.

### Reproducing the issue.

I play as an evoker.  When switching specs from devastation and then to preservation, I am noticing that my macro/spell positions on the action bars are not saving and staying in the desired position.  However, what does happen is the difference in macro/spell position gets completed removed (blank action button on action bar).  Is there way to have this fixed?  I have tried to do the /edebug on command and the problem still exists.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
This is a blizzard issue - ElvUI doesn’t handle the spells on the action bars, it is handled by blizzard.  

See below for the known issues which this is included and the workaround for it. 

**Patch 11.0.2**

<a:alert:1038825900000677908> Update to ElvUI 13.75
Please remember to check <#1036757241413517383>

`ActionBars`
Spells keep getting cleared and don't stay on bars **[BLIZZARD ISSUE, READ HERE](https://us.forums.blizzard.com/en/wow/t/everything-on-hotbars-keeps-getting-cleared/1900167)**
Workaround: You have to create a talent loadout and save it with a name.

`Bags`
If you cant open your Bags and get an error about ItemButtonTemplate then do the following steps:
Turn off all addons, open your bags, delete any artifact(conduit) items, turn addons back on.

`Range Fader`
Mostly fixed in 13.75 but Hero Talents while leveling from 70-80 will still have the possibility
to break it again. We're working on it. No ETA.

Known so far:
- Deathstalker Assassination Rogue

`Warband Bank`
If you don't have any filters set, the item deposit will go in tab 1 instead of the currently selected tab.
This happens in the default Blizzard frame as well, there is currently no fix for it.
Drag and drop for this as a workaround should work as expected.

**Comment by kodewdle** [comment]
this is listed as a Blizzard Issue; closing this ticket because the location of your spells is not saved by ElvUI
