### ISSUE TITLE
Assassination Rogue Target Unitframe Range Fader Incorrect

### ISSUE THREAD

**Issue by twilite69** [tukui-org/ElvUI#1321]
### Troubleshooting Steps

Updated ElvUI to 13.75 target uniframe for nuetral and hostile target is faded out. Target self and other player unitframes normal fader. Occurs on the Assassination spec for rogue, Outlaw spec is normal. See the 
![Screenshot 2024-08-24 080857](https://github.com/user-attachments/assets/138bc553-57b5-4aef-9579-ba8a61c1f90d)
![Screenshot 2024-08-24 081047](https://github.com/user-attachments/assets/9bd9cfc5-37f5-4d46-b3ec-456b94afb731)

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
Yes, that is a known issue.    Copied from the discord known issue. 

**Patch 11.0.2**

<a:alert:1038825900000677908> Update to ElvUI 13.75
Please remember to check <#1036757241413517383>

`ActionBars`
Spells keep getting cleared and don't stay on bars **[BLIZZARD ISSUE, READ HERE](https://us.forums.blizzard.com/en/wow/t/everything-on-hotbars-keeps-getting-cleared/1900167)**
Workaround: You have to create a talent loadout and save it with a name.

`Bags`
If you cant open your Bags and get an error about ItemButtonTemplate then do the following steps:
Turn off all addons, open your bags, delete any artifact(conduit) items, turn addons back on.

`Range Fader`
Mostly fixed in 13.75 but Hero Talents while leveling from 70-80 will still have the possibility
to break it again. We're working on it. No ETA.

Known so far:
- Assassination Rogue

`Warband Bank`
If you don't have any filters set, the item deposit will go in tab 1 instead of the currently selected tab.
This happens in the default Blizzard frame as well, there is currently no fix for it.
Drag and drop for this as a workaround should work as expected.

**Comment by 1Botanica1** [comment]
It should be mainly fixed in the dev version. 

You can download & install to test https://api.tukui.org/v1/download/dev/elvui/main
Or wait until next version of ElvUI, no ETA

**Comment by kodewdle** [comment]
fixed in 13.76

**Comment by Rainwtr** [comment]
The update fixed most of my characters except for 1.  is there something I can reset on that one character correct this issue that we know of?

**Comment by 1Botanica1** [comment]
From discord 

### Classic Era
> you will have to check `Show all spell ranks` in Spellbook.  This is no longer optional as the APIs require it.
### Retail
> Hero talents may break range, post `/estatus` along with talents page in <#222356141785612288> if you have issues.

**Comment by Rainwtr** [comment]
That did the trick thank you
