### ISSUE TITLE
[Retail Bug Report] <ElvUI not opening within game>

### ISSUE THREAD

**Issue by RapidDonut** [tukui-org/ElvUI#137]
### What is the issue you are having?

Cannot click on ElvUI in in-game menu or use /elvui in chat option

### What is the expected behavior?

Would normally open ElvUI options menu

### What actually happened?

Nothing happens

### Suggested Solution/Workaround

Have already updated all add ons, the problem still persists. I disabled all add ons except ElvUI, the problem still persists. I deleted the ElvUI folders out of the Add Ons folder, redownloaded and reinstalled, the problem still persists.
Posted this previously and was closed before I could explain I had already updated add ons so any other suggestions would be much appreciated.

### Errors

```shell
Message: Interface\AddOns\ElvUI\Core\Config.lua:1091: hooksecurefunc(): Open is not a function
Time: Sat Jan  8 13:40:46 2022
Count: 1
Stack: Interface\AddOns\ElvUI\Core\Config.lua:1091: hooksecurefunc(): Open is not a function
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Core\Config.lua"]:1091: in function `ToggleOptionsUI'
[string "@Interface\AddOns\ElvUI\init.lua"]:213: in function <Interface\AddOns\ElvUI\init.lua:212>

Locals:
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog) and done the [Troubelshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28).

**Comment by RapidDonut** [comment]
Message: Interface\AddOns\ElvUI\Core\Toolkit.lua:138: attempt to call method 'SetBackdrop' (a nil value)
Time: Sat Jan  8 15:16:07 2022
Count: 1
Stack: Interface\AddOns\ElvUI\Core\Toolkit.lua:138: attempt to call method 'SetBackdrop' (a nil value)
[string "=[C]"]: in function `SetBackdrop'
[string "@Interface\AddOns\ElvUI\Core\Toolkit.lua"]:138: in function `SetTemplate'
[string "@Interface\AddOns\ElvUI\Modules\Skins\Addons\Ace3.lua"]:446: in function `Ace3_StyleTooltip'
[string "@Interface\AddOns\ElvUI\Modules\Skins\Addons\Ace3.lua"]:477: in function `Ace3_SkinTooltip'
[string "@Interface\AddOns\ElvUI\Modules\Skins\Addons\Ace3.lua"]:580: in function <Interface\AddOns\ElvUI\Modules\Skins\Addons\Ace3.lua:569>
[string "=[C]"]: in function `NewLibrary'
[string "@Interface\AddOns\ElvUI_OptionsUI\Libraries\Ace3\AceGUI-3.0\AceGUI-3.0.lua"]:29: in main chunk
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Core\Config.lua"]:1069: in function `ToggleOptionsUI'
[string "@Interface\AddOns\ElvUI\init.lua"]:213: in function <Interface\AddOns\ElvUI\init.lua:212>

Locals:

**Comment by Azilroka** [comment]
Because 1 the path would be.. Interface\AddOns\ElvUI\Core\General\Config.lua

You have ElvUI 12.44 or below.

**Comment by Azilroka** [comment]
- [ ] Make sure ElvUI is updated.
- [ ] Search. Make sure your issue hasn't been covered already by doing a forum search.
- [ ] Check current tickets in the Ticket Tracker to make sure your issue is not a bug which has been reported already.
- [ ] If you're 100% sure the issue is a bug in ElvUI then make a ticket in the Ticket Tracker instead of creating a post in the Technical Support forum.
- [ ] Use a title which describes your problem. "Something is wrong" is NOT a proper title. "Actionbars are not responding to key clicks" would be a proper title if you experience issues with clicking your actionbars.
- [ ] *Always* provide the version of your ElvUI installation (do not say 'latest version', we want the actual number). Use the /estatus command ingame.
- [ ] Did you disable all addons except the two called 'ElvUI' and 'ElvUI OptionsUI'? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.
- [ ] Did you disable all addons and try to reproduce the issue? This is important in order to rule out that the issue is with the WoW client and not with ElvUI.
- [ ] Are lua errors set to show up when they happen (/luaerror on)? If you received any errors then make sure you post the *first* error you received (press the 'Prev' / 'Back' button until you see the very first error)
- [ ] Describe your issue with as much detail as possible. The more info you provide, the better and faster support you will receive. What were you doing when the problem occurred? Explain how people can reproduce the issue.
- [ ] A picture is worth a thousand words. We often get clues about the issue by looking at your entire UI, so please include some screenshots.
- [ ] Please do not upload with Imageshack. Use a proper host such as Imgur, or any other host which gives access to direct links and doesn't force rescale of images by default.
