### ISSUE TITLE
[Retail Bug Report] Power text keeps reattaching to Health Frame instead of designated Power frame. 

### ISSUE THREAD

**Issue by reign1221** [tukui-org/ElvUI#15]
### What is the issue you are having?

Power text in the wrong place from time to time. No other addons enabled.

https://media.discordapp.net/attachments/222356141785612288/898551226373931018/unknown.png?width=1202&height=676

### What is the expected behavior?

The power text is a custom text set to be attached to the power frame, it keeps reattaching itself to the health frame after a few moments, and I need to /refresh so the power text goes back to the designated frame.

### What actually happened?

That's all there is.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://changelogurlhere.com) and done the [Troubelshooting Steps](https://urlfortroubleshootingstepshere.com).

**Comment by qpwnedbxd** [comment]
Same thing happens to me as well, I suspect is has to do with detaching the Power Bar from the UnitFrame and the Auto Hiding options. Also in my case I am using a Custom Text instead for the sole reason that I use the Class Bar on top of the Power Bar and I want the text to be on top of both instead of the Class Bar overlappig the text.

**Comment by kodewdle** [comment]
yes, this was caused because of the hidden power bar sometimes, code evolved and that was missed! thank you :)

- sorry this one took a bit longer to fix
