### ISSUE TITLE
[TBC Bug Report] Micro-Menu broken since last update (2.19)

### ISSUE THREAD

**Issue by DrSterni** [tukui-org/ElvUI#30]
### What is the issue you are having?

The micromenu is shown, but sort of broken since the last update. It seems to be split up between the third and the fourth button, the lower half is a bit pushed to the right side.

### What is the expected behavior?

The micromenu should be shown as a usual row (in my case from top to bottom).

### What actually happened?

The micromenu is shown, but sort of broken since the last update. It seems to be split up between the third and the fourth button, the lower half is a bit pushed to the right side.

### Suggested Solution/Workaround

Workaround: Switch "Keep size ratio" off and on again. Works for some time, but gets back to the error after a while. Don't know why.

### Errors

```shell
---
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org).

**Comment by MMoisa** [comment]
An easy way to reproduce this issue is to set the buttons per row for the micro bar to 1 so that the micro bar sits vertically instead of horizontally on the screen. The moment you hit the escape key or you click one of the the top 3 buttons the rest of the buttons will get shifted to the right.
![WoWScrnShot_110621_092432](https://user-images.githubusercontent.com/13348851/140601696-fe90c0de-b3be-4861-81ea-e895dcef411c.jpg)
![WoWScrnShot_110621_092441](https://user-images.githubusercontent.com/13348851/140601697-10744698-edcc-45d8-9ff8-36e6b376692c.jpg)

**Comment by DrSterni** [comment]
Sorry it took a while... That is exactly what I meant. Just to prove it: Here's the screenshot of mine :-)
![broken_mini_menu](https://user-images.githubusercontent.com/48457416/140605037-99062f06-1150-438d-ad21-30ded1d53c67.jpg)
.
