### ISSUE TITLE
[Wrath Bug Report] <Heal Prediction missing for end wrath spells>

### ISSUE THREAD

**Issue by jurasekdominik** [tukui-org/ElvUI#390]
### What is the issue you are having?

Both me and my friend are having the same issue for wrath spell ranks. 
Heal prediction is working for older ranks but not for newer ones. I checked HealCommLib and they are in the rank table.

Greater Heal (Rank 7) works, (Rank 8) doesnt
Flash Heal (Rank 9) works, (Rank 10) doesnt
Holy Light (Rank 11) works, (Rank 12) doesnt
Flash of Light (Rank 8) works, (Rank 9) doesnt

### What is the expected behavior?

To see heal prediction for all spell ranks

### What actually happened?

Mentioned higher ranks of same spell dont show up heal prediction

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
It doesn't currently work for ALL WRATH ranks. THIS IS A BLIZZARD ISSUE.

**Comment by sn1pah** [comment]
Tukui and Elvui using different method for heal prediction?
Cose in Tukui it works for new ranks but not in Elvui :(

**Comment by Azilroka** [comment]
@sn1pah yes, Tukui relies on LibHealComm fully.

**Comment by coolmodi** [comment]
@Azilroka is there a reason why ElvUI relies fully on the Blizzard API for direct heals even though it sucks in classic? I made a fork for myself because of this, also because seeing the full HoT duration is not usefull at all imho. I use HealComm for everything and the Blizzard API as a fallback if needed in case there's incomming direct heal not known to HealComm, while limiting shown prediction from HealComm to x seconds into the future.

**Comment by Azilroka** [comment]
@coolmodi , Well Blizzard was supposed to be taking the ball on healing predictions in TBC. If I have to work around every single failure then the code base will be larger. If I do use LibHealComm then I have to deal with people saying it's causing disconnects.. the spell data calculations are off.. and literally crying because they'll want to filter out some of the hots.. have hots as a different color.. hots a different color per tick.. other heals as their class colors.. personal heals as another color.
