### ISSUE TITLE
Enabling Action Bars deletes LFG Eye

### ISSUE THREAD

**Issue by jonathanjosephduarte** [tukui-org/ElvUI#416]
### What is the issue you are having?

Enabling action bars automatically hides the bottom right blizzard menu that now contains the LFG Eye (Which is no longer on the minimap unless you use the minimap module for elvui).

This makes it so that you can't use the Action bar module independently of the minmap module if you want to have the LFG Eye.

The eye also does not appear in the micro bar
![image](https://user-images.githubusercontent.com/49081510/197934399-cd7e5d59-46cd-428e-a885-192fb2ffb347.png)
![image](https://user-images.githubusercontent.com/49081510/197934485-f59f1bce-cd0b-4f6e-88f1-c0752a8d08dc.png)

### What is the expected behavior?

Activate the micro bar option in the Action bar Module and the LFG Eye is there (like it is in the new default UI)

### What actually happened?

The LFG Eye is hidden permanently unless a separate ELVUI module is activated

### Suggested Solution/Workaround

Add the Eye element to the micro bar or make it an independent element that we can move around

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
Well that is tech working as intended.  We have it attached to the minimap and there are options in the Maps -> Minimap -> Queue Status section (no option to remove it from the minimap).

**Comment by Repooc** [comment]
i did find a bug if u have the option in Maps -> Minimap -> Disable Cluster unchecked, the eye doesnt seem to show.

**Comment by alloskanenas** [comment]
> Well that is tech working as intended. We have it attached to the minimap and there are options in the Maps -> Minimap -> Queue Status section (no option to remove it from the minimap).

Blizzard's default minimap does not have the lfg eye so it is not visible when only the Elvui minimap module is disabled. The only way to make it visible, if you prefer Blizzard's default minimap, is by also disabling Elvui's action bars.
Meaning that when using the default minimap along with elvui's action bars the eye is nowhere to be seen.

**Comment by Zetaprime82** [comment]
> i did find a bug if u have the option in Maps -> Minimap -> Disable Cluster unchecked, the eye doesnt seem to show.

i had the Disable Cluster checked and it still wouldt show up so i had to uncheck the re-check Disable Cluster in order to make it show up

**Comment by ArcasDevlin** [comment]
I made an account here to come help if I could. 

This is still an issue. I use sexymap and was fighting with the problem most of yesterday. 

I did find a solution: 

1) Grab an addon called "Hiding Bar".
2) Temporarily turn on Elvui's map and enter a queue so that they eye pops up.
3) Go into Hiding Bar's options. On the third tab, "Options of adding buttons", click Point to button, then click on the eye. It will add it to your bar. It will be there permanently, whether you're in queue or not, but when you hover over it whilst in queue, it will have the proper information.
4) You can place this bar wherever you like and place other minimap buttons on it as well (or not). You could have only this on it if you want it and put it wherever. 
5) Turn Elvui's map back off. In my case, I turned it off and Sexymap back on. And the queue button was still there.
Mine is below my chat in the lower left. 
![image](https://user-images.githubusercontent.com/116835913/198362780-bbbed0a0-f065-499a-873e-cd96b33873f8.png)

I hope this helps someone.

**Comment by Zetaprime82** [comment]
Ah nice guide [ArcasDevlin](https://github.com/ArcasDevlin) you just beat me to the same guide xD

**Comment by jonathanjosephduarte** [comment]
This is the exact issue i am having, down to the interaction with sexymap - thank you for the work around!

**Comment by Demokdawa** [comment]
To add to the issue, the "blizzard" bar does not appear if you disable "micro bar" part of elvui. 

The behaviour should be to default back to blizzard UI, but it's not the case here (same issue with bags).

**Comment by YWI** [comment]
Yeah... ALthough one of the biggest reasons I'm using elvui is because of the actions bars.  I hope a fix is released soon.
