### ISSUE TITLE
[Classic Bug Report] Enemy cast bar not working correctly

### ISSUE THREAD

**Issue by bobjackson321** [tukui-org/ElvUI#46]
### What is the issue you are having?

When an enemy mob casts a spell, the cast bar on both the target frame and nameplate does not display.

### What is the expected behavior?

Enemy cast should display immediately display when cast starts.

### What actually happened?

Enemy casts do not display unless you deselect/run out of nameplate distance, then re-select/run back into range before the spell is complete. Tested on classic era realm and season of mastery beta realm with only elv ui enabled.

https://user-images.githubusercontent.com/45326365/140616066-afaff165-dbba-4b39-a089-14a8e14b2481.mp4

### Suggested Solution/Workaround

Other addons such as ClassicCastbars is showing cast bars correctly.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org).

**Comment by Azilroka** [comment]
ClassicCastbars is not powered by LibClassicCasterino.. So comparing that against ElvUI isn't the same.

**Comment by bobjackson321** [comment]
Sorry i dont even know what that means. I'm just saying it works in another addon so its not a blizzard issue. 1.14 added UnitCastingInfo API if that helps.

**Comment by Azilroka** [comment]
It means.. They are not using this. https://github.com/rgd87/LibClassicCasterino
We are. They have custom code for it running and of course it will function as it is not the same.

`I'm just saying it works in another addon so its not a blizzard issue.`

It's not a blizzard issue because 1) It's not their code. 2) They don't support it natively.

`1.14 added UnitCastingInfo API if that helps.`
Yes, It was added. It still only returns for the player unit.

1.14.1 or 1.14.2 Should fix that to allow the query of other units.

**Comment by Azilroka** [comment]
https://github.com/Stanzilla/WoWUIBugs/issues/184
