### ISSUE TITLE
[Retail Bug Report] <Elvui not loading>

### ISSUE THREAD

**Issue by Fortex365** [tukui-org/ElvUI#460]
### What is the issue you are having?

I've got 12.95 latest version to retail and it doesn't load, its ticked for all characters / or for specific, and it doesnt work at all. Doesn't write anything to chat, no elvui window via /elvui etc.

### What is the expected behavior?

Override blizzard ui with elvui and its all componenets

### What actually happened?

After pre-patch update was pushed out and downloaded previously installed elvui did no longer work and newly downloaded aswell

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
This is due to the fact that you are overwriting the files and not deleting and reinstalling the addon like you should be doing.. As 75% of our user base seems to be under the impression that all addon settings are stored in the addon itself while that isn't the case. Interface\AddOns is considered read only for addons and cannot write there. The WTF folder is where all addon settings are stored.
