### ISSUE TITLE
[Retail Bug Report] <talking head >

### ISSUE THREAD

**Issue by ShilDrack** [tukui-org/ElvUI#471]
### What is the issue you are having?

the talking head cannot move
![WoWScrnShot_102922_180351](https://user-images.githubusercontent.com/116979996/198852647-13f587b5-d137-46cc-8845-c54f6451ecc6.jpg)
![WoWScrnShot_102922_180356](https://user-images.githubusercontent.com/116979996/198852653-74af864e-1cb2-4978-be57-0daf5dde6b28.jpg)

### What is the expected behavior?

It should be able to be selectable and be able to move it to a more comfortable position

### What actually happened?

Doing M + the talking head came out in the center, check options in elvui to deactivate it, in the new blizzard interface it can be moved, but not deactivated.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by UnaffiliatedGamer** [comment]
Same issue here. Verified it was ElvUI causing the issue. For me, the TalkingHeadFrame no longer has an ElvUI place anchor, which is to be expected now that Blizz have their own version. The problem is that ElvUI is overriding the Blizzard anchor hooks the talking head to the "Loot / Alert Frames (Grow Up)" anchor. The talking head does shift and align with the other alerts and loot popups, so it looks like an intended feature but without a menu option that I can find.
