### ISSUE TITLE
Flyout Work Around until Blizzard fixes the bug

### ISSUE THREAD

**Issue by SteveEbey73742** [tukui-org/ElvUI#495]
### What is the issue you are having?

As suggested in the title, is there a way to tell Elvui not to take over the flyout, and let that use the standard blizzard one, from the New UI for DragonFlight?

### What is the expected behavior?

A work around for the Blizzard bug, by disabling the Elvui portion of the interface that controls flyout.

### What actually happened?

Discovered that the issue is Blizzard, not Elvui.  Asking for steps to disable the flyout control in Elvui.

### Suggested Solution/Workaround

Disable flyout in the Elvui interface, until Blizzard fixes the bug they created.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Caedis** [comment]
![image](https://user-images.githubusercontent.com/18713839/199591091-e4ddaf2f-df9d-43ad-b007-fe81d309b80d.png)

also, no workaround because its on their end to fix it. We have tried all we can think of.

No other addon bars have flyouts working and Bartender even states that its Blizzard as well.
![image](https://user-images.githubusercontent.com/18713839/199591247-afd6d825-ce77-4805-8d4c-4aa81fcdb5fa.png)
