### ISSUE TITLE
About licensing and the risk taken by ElvUI

### ISSUE THREAD

**Issue by Vardex** [tukui-org/ElvUI#553]
This ticket purpose is to try to make the ElvUI team and the wow addon dev community understand a bit more about licensing and explain the risk that the ElvUI is currently taking.

## What is a license?

A license is a legal instrument governing the use or redistribution of software. 
A typical license grants the licensee permission to use one or more copies of software in ways where such a use would otherwise potentially constitute copyright infringement of the software owner's exclusive rights under copyright.

## What is a license violation?

You are in violation of a license if you do something like distribution or modification of a software without being given the permission by the license or without respecting the conditions of the license.

## What about the case of a project without a license?

A project without a license is under exclusive copyright. Nobody have the right to copy, distribute or modify the project.
By publishing on github, the project grant right to github to allow users to view the code and fork it.

## The case of ElvUI

ElvUI have two major problems:
- The distribution of libraries without having explicit permissions. That mean that at any moment the copyright owner can ask you to remove their work from your project.
#547 is not really useful as you are also in violations of the license of some other libraries, like all the all right reserved one. Also the copyright owner have to report the problem, and I guess in most case, library author want their project to be used, so they won't do that. But it's a risk for ElvUI, at any point any of these library author could ask for their library to be removed from ElvUI.
To avoid that, ElvUI should try to only accept libraries that give them permission to distribute them, and try to reduce reliance on libraries that don't give them that right.
- Accepting code from people without proper foss license or signing a contributor license agreements. ElvUI is accepting contributions, those contributions are almost all also under an all right reserved license, that mean that all the code merged in ElvUI are in license violation of the contributor. At any moment a contributor could use their rights to ask for their code to be removed from ElvUI.
To avoid that, ElvUI should make contributors sign a contributor license agreement giving their rights to ElvUI or ask people to license their code under a foss license.

**Comment by drsleo** [comment]
stop creating these tickets here, this is not what this is for. As far as I know you have nothing to do with it either, but as I don't know anything...
how stupid, rights to something that is not registered and idea or conversation... have patience, addons are made to help each other, nobody is selling anything. stop being a child,

**Comment by Azilroka** [comment]
@drsleo, This isn't the same person who you think it is. This is another author that we have contact with and is providing actual feedback in this ticket format.

**Comment by nihilistzsche** [comment]
I agree they should do that, but they did not in the past, so I am within my rights to request code derived from my code to be removed, and I have, and if it is not, I will report the repository to github for violating my copyright.  I will not keep fighting any of this, I will let them deal with it, and at the end of the day, we either come to an agreement here or things could get much much worse.

**Comment by Azilroka** [comment]
https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#6-contributions-under-repository-license

We're in the process of asking about this with Github. According to the language here. Inbound = Outbound and any code submitted belongs to the Tukui-org organization owners which is Elv and Simpy.

We will be doing a CLA going forward.

Now to the topic of other License Violations:
https://us.forums.blizzard.com/en/wow/t/ui-add-on-development-policy/24534

Blizzard's policy states:
`1) Add-ons must be free of charge.
All add-ons must be distributed free of charge. Developers may not create “premium” versions of add-ons with additional for-pay features, charge money to download an add-on, charge for services related to the add-on, or otherwise require some form of monetary compensation to download or access an add-on.`

Which violates the terms of GLP v2 / GPL v3 which means any addon which uses those License is in Violation of WoW's Addon Policy.

How?

GPL v2 / GPL v3
`For example, if you distribute copies of such a program, whether gratis or for a fee, you must give the recipients all the rights that you have. You must make sure that they, too, receive or can get the source code. And you must show them these terms so they know their rights.

You may charge any price or no price for each copy that you convey, and you may offer support or warranty protection for a fee.`

WoW's AddOn Policy Restricts GPL which according to it's rules.. is a violation of it's License and it cannot be used.

**Comment by Vardex** [comment]
> We're in the process of asking about this with Github. According to the language here. Inbound = Outbound and any code submitted belongs to the Tukui-org organization owners which is Elv and Simpy.

From my understanding, it mean that any code contributed use the same license that mean that all code contributed are under ARR. Just like when contributing to a GPL project, you contribute GPL code. But the author of that code is still the copyright owner. Info about no license which suggest using a CLA to avoid that problem: https://choosealicense.com/no-permission/

> Now to the topic of other License Violations

Your other point is a bit off-topic and I believe wrong. Blizzard policy is a policy about being authorized to load your addon in the game. It doesn't have really anything to do with the topic I wanted to talk about. If using the same logic it violate ElvUI license and most other licenses.
My point was that ElvUI is violating GPL license but is also violating some ARR licenses. And that even if they do, it's the copyright owner that should decide if they want to act on that violation, and I believe most if not all want their libraries to be used so wouldn't. But that still open a risk to ElvUI. So deciding to act only on GPL licensed library appear a bit illogical.
