### ISSUE TITLE
[Retail Bug Report] <level up in the combat Error>

### ISSUE THREAD

**Issue by Bin0729** [tukui-org/ElvUI#633]
### What is the issue you are having?

level up in the combat

### What is the expected behavior?

Not getting a lua error

### What actually happened?

questbar  disabled

### Suggested Solution/Workaround

No response

### Errors

```shell
1x [ADDON_ACTION_BLOCKED] 插件 'ElvUI' 尝试调用保护功能 'ObjectiveTrackerFrame:SetPointBase()'。
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPointBase'
[string "@FrameXML/EditModeSystemTemplates.lua"]:62: in function `SetPoint'
[string "@FrameXML/EditModeSystemTemplates.lua"]:184: in function `ApplySystemAnchor'
[string "@FrameXML/EditModeSystemTemplates.lua"]:1789: in function `ApplySystemAnchor'
[string "@FrameXML/EditModeSystemTemplates.lua"]:202: in function `UpdateSystem'
[string "@FrameXML/EditModeManager.lua"]:1015: in function `UpdateSystem'
[string "@FrameXML/EditModeManager.lua"]:1008: in function `UpdateSystems'
[string "@FrameXML/EditModeManager.lua"]:882: in function `UpdateLayoutInfo'
[string "@FrameXML/EditModeManager.lua"]:239: in function <FrameXML/EditModeManager.lua:231>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by voidbeast** [comment]
I am not entirely sure what this issue is trying to describe, but I think it might be the same issue I am having? Possibly.
Every time I gain a level (and I believe it is only gaining a level while in combat) the objective frame does something weird. I've had it move all the way across the screen from the right side to the furthest top left corner of the screen by itself, and I've had all the text disappear from the objective frame leaving only the icons visible. One of those two things seems to happen every time I gain a level in combat across multiple characters. Reloading the UI puts it right. 

I haven't had logging on until now so I'll try to see if it matches this error OP posted next time it happens.

**Comment by RAtwood90** [comment]
U both did:

Troubleshooting Steps (ElvUI)
Do these steps in order.

Type in chat in game /edebug on
Test - Do you still have the issue?
If you still have the issue/error - type in chat in game /estatus
Upload a full, uncropped screenshot showing the issue and the estatus.
If you are finished with debugging, you can enable your AddOns back with: /edebug off

I get no Errors was also leveling Alts through the Event.

**Comment by Bin0729** [comment]
@RAtwood90 
![WoWScrnShot_112922_133329](https://user-images.githubusercontent.com/118101894/204449624-eb7fb1ce-26b9-411d-b9e7-eb850a55fb30.jpg)
![WoWScrnShot_112922_133817](https://user-images.githubusercontent.com/118101894/204449668-140ae463-1f21-4e8e-b937-f2773d3bc910.jpg)

**Comment by voidbeast** [comment]
Yes, that is exactly what mine is doing too. Thank you @Bin0729. I got wrapped up in dragonflight stuff so I didn't get around to trying to set this up again for a screenshot. But that's precisely what mine looks like when it has happened to me too. Other than that, sometimes instead of making the text disappear, it will make the objective frame move all the way across the screen from the right side where the one in this screenshot is, to the very top left 0,0 position.
