### ISSUE TITLE
[Feature Request] Cardinal direction option on minimap

### ISSUE THREAD

**Issue by StirlingDC** [tukui-org/ElvUI#750]
There is no effective way to navigate when rotateMinimap is enabled. Prior to Dragonflight, I was able to use rotateMinimap with ElvUI and there were markers for cardinal directions on the minimap. Since Dragonflight's UI changes, there are now no directional indicators. Screenshot attached of what I could see prior to DF. 

Adding an option to show cardinal directions at the corners of the minimap would solve this issue.

I don't think there are reasonable alternatives to this issue, and would disagree that disabling minimap rotation is a valid solution. I had been using ElvUI with minimap rotation for years before it stopped working; I don't mind the "clipping" that happens with a square map, I do mind not being able to navigate anymore. The only alternative I am considering is not using ElvUI for the minimap, and using another addon instead, as Repooc suggested on Discord in December. 

Possibly related addons that no longer appear to be maintained:
https://www.curseforge.com/wow/addons/elvui-cardinal-points
https://addonswow.com/elvui-compass-points

Screenshot highlighting what I used to see prior to DF:
![elvui_minimap_cardinal](https://user-images.githubusercontent.com/122285461/211326953-325c6c92-82e8-4000-9464-cd0671317ee1.jpg)

**Comment by Repooc** [comment]
Wow has redone their minimap and those cardinal direction points were from their minimap before they altered it.  We have never supported the rotating minimap option from blizzard, so with them changing and replacing those cardinal locations, we no longer have them showing.  The way they do it now just looks horrible on our minimap which is why I would recommend a minimap addon to replace our minimap if you would like some more customizable ways to alter the minimap.

https://github.com/tukui-org/ElvUI/assets/1479745/c813c205-dc0e-47eb-ac33-11de81a5bb80

Even if you can look past the horrible look of the rotating minimap, the texture looks horrible and doesnt fit (look wise as the scaling could be adjusted technically)
