### ISSUE TITLE
[Retail Bug Report] Action Bars disappeared 

### ISSUE THREAD

**Issue by GOOESQ** [tukui-org/ElvUI#787]
### What is the issue you are having?

Action Bars not showing when you log in on newest WoW update. Problem confirmed across two machines, separate accounts. Resetting to default settings does not bring them back.

### What is the expected behavior?

Action bars show up

### What actually happened?

They don't show up 

### Errors

```shell
Message: ...ce/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua:356: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
Time: Tue Jan 24 18:28:36 2023
Count: 1
Stack: ...ce/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua:356: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua"]:210: in function <...lvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:118>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua"]:356: in function `SetupMicroBar'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua"]:1700: in function <.../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:1646>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1796: in function `CallLoadFunc'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1811: in function `CallLoadedModule'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1837: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1946: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:223: in function <Interface/AddOns/ElvUI/Core/init.lua:222>
[string "=[C]"]: ?
...
[string "@Interface/FrameXML/UIParent.lua"]:544: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:753: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by GOOESQ** [comment]
This error message is indicating that there is an issue with the SecureHook function in the file "MicroBar.lua" on line 356. Specifically, it appears that the function is attempting to hook a non-existing target.

Based on the error message, it appears that the addon ElvUI is trying to use the SecureHook function to hook onto a method or object that does not exist. The SecureHook function is used to hook onto a specific method of an object, allowing the addon to execute its own code in response to that method being called.

To fix this error, you will need to locate the specific line of code that is causing the issue, and then determine what the intended target for the hook was. One possible reason for this error is that the hook is trying to hook onto a non-existing method or object or the hook is being called before the object has been created.

If the hook is being called before the object has been created, it may be helpful to move the hook call to a later point in the code, after the object has been created, or alternatively, you could use a delayed call to the hook function using a timer.

**Comment by GOOESQ** [comment]
If you delete the 3 lines of SecureHook code the bars come back

**Comment by kanzelm3** [comment]
+1

**Comment by raijingaijin** [comment]
Just wanted to add that I'm experiencing the exact same issue as posted across multiple PCs and multiple characters. Specific to 10.0.5. Using ElvUI 13.21.

**Comment by blackjack1031** [comment]
I am having this issue as well along with my bag bar and micro bar displaying as well. Here are my error

Message: Interface/AddOns/Raidbot/Raidbot.lua:66: attempt to call global 'RegisterAddonMessagePrefix' (a nil value)
Time: Tue Jan 24 16:47:45 2023
Count: 1
Stack: Interface/AddOns/Raidbot/Raidbot.lua:66: attempt to call global 'RegisterAddonMessagePrefix' (a nil value)
[string "@Interface/AddOns/Raidbot/Raidbot.lua"]:66: in main chunk

Locals: _G = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined =[C]:-1
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 SettingsSliderOptionsMixin = <table> {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 HUD_EDIT_MODE_SETTING_ACTION_BAR_HIDE_BAR_ART = "Hide Bar Art"
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 774
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 417
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this community."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 OPTION_TOOLTIP_SHOW_MULTIBAR4 = "Attached to the left side of Right Action Bar 1 by default"
 LE_GAME_ERR_INVALID_FOLLOW_PVP_COMBAT = 371
 MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
 }
 PROFESSIONS_COLUMN_REAGENTS_NONE = "None"
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 CHAT_HEADER_SUFFIX = ": "
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 COVENANT_MISSIONS_HEALTH = "Health"
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @Interface/FrameXML/UnitFrame.lua:898
 PVPReadyDialogBottomArt = PVPReadyDialogBottomArt {
 }
 MultiBar6Button4Flash = MultiBar6Button4Flash {
 }
 DUNGEON_FLOOR_UPPERBLACKROCKSPIRE3 = "Hall of Blackhand"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 FCFDockOverflowButton_OnClick = <function> defined @Interface/FrameXML/FloatingChatFrame.lua:2394
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 MoneyFrame_OnEvent = <function> defined @Interface/FrameXML/MoneyFrame.lua:202
 BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Blizzard services may be unavailable."
 AutoCompleteEditBox_OnKeyDown = <function> defined @Interface/FrameXML/AutoComplete.lua:368
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LFGTeleport = <function> defined =[C]:-1
 LE_GAME_ERR_ONLY_ONE_QUIVER = 36
 INT_SPELL_DURATION_HOURS = "%d |4hour:hrs;"
 ToggleEncounterJournal = <function> defined @Interface/FrameXML/UIParent.lua:1151
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
 }
 ROGUE_COMBAT_CORE_ABILITY_4 = "Melee attack that spends Combo Points."
 JoinSkirmish = <function> defined =[C]:-1
 MultiBarRightButton7Shine9 = MultiBarRightButton7Shine9 {
 }
 BankFrameItem17SearchOverlay = BankFrameItem17SearchOverlay {
 }
 AUCTIONATOR_L_DEFAULT_LIST_HEADER = "Default Shopping List"
 DMG_LCD = "DMG"
 ACTION_SPELL_MISSED_POSSESSIVE = "1"
 Is64BitClient = <function> defined =[C]:-1
 SecureCmdItemParse = <function> defined @Interface/FrameXML/ChatFrame.lua:1156
 SLASH_STOPATTACK1 = "/stopattack"
 MultiCastActionButton4HotKey = MultiCastActionButton4HotKey {
 }
 MultiBar5Button11Shine4 = MultiBar5Button11Shine4 {
 }
 TutorialFrame_OnMouseDown = <function> defined @Interface/FrameXML/TutorialFrame.lua:262
 ContainerFrame4Item16Cooldo
Message: ...ce/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua:356: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
Time: Tue Jan 24 16:47:47 2023
Count: 1
Stack: ...ce/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua:356: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua"]:210: in function <...lvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:118>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua"]:356: in function `SetupMicroBar'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua"]:1700: in function <.../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:1646>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1796: in function `CallLoadFunc'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1811: in function `CallLoadedModule'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1837: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1946: in function <Interface/AddOns/ElvUI/Core/General/Core.lua:1915>
[string "=[C]"]: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:223: in function <Interface/AddOns/ElvUI/Core/init.lua:222>
...
[string "@Interface/FrameXML/UIParent.lua"]:544: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:753: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals: <none>
Message: ...dOns/ElvUI_BenikUI/modules/actionbars/actionbars.lua:94: attempt to index field 'backdrop' (a nil value)
Time: Tue Jan 24 16:47:48 2023
Count: 1
Stack: ...dOns/ElvUI_BenikUI/modules/actionbars/actionbars.lua:94: attempt to index field 'backdrop' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_BenikUI/modules/actionbars/actionbars.lua"]:94: in function `StyleColor'
[string "@Interface/AddOns/ElvUI_BenikUI/modules/actionbars/actionbars.lua"]:195: in function `Initialize'
[string "@Interface/AddOns/ElvUI_BenikUI/init.lua"]:54: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI_BenikUI/init.lua"]:80: in function `?'
[string "@Interface/AddOns/ElvUI_Libraries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua"]:299: in function <...aries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua:295>
[string "=[C]"]: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:223: in function <Interface/AddOns/ElvUI/Core/init.lua:222>
[string "=[C]"]: ?
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...ce/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...ce/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:544: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:753: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals: 

Message: Interface/AddOns/Raidbot/Raidbot.lua:1 (null)
Time: Tue Jan 24 16:47:50 2023
Count: 1

Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/Raidbot/Raidbot.lua:1 (null)
Time: Tue Jan 24 16:47:50 2023
Count: 1

**Comment by Mace1959** [comment]
same issue

**Comment by ajamafalous** [comment]
> 

You don't even need to do this much; just comment out line 1700 in ActionBars.lua

**Comment by ajamafalous** [comment]
> **WORKAROUND TO TEMP FIX**
> 
> Go to C:\Program Files (x86)\World of Warcraft_retail_\Interface\AddOns\ElvUI\Core\Modules\ActionBars Open up MicroBar.lua with notepad CTRL-F SecureHook delete those 3 lines of code messes with micro bar but it works for now

You don't even need to do this much; just comment out line 1700 in ActionBars.lua

**Comment by jgz** [comment]
Also experiencing all of the above,  commenting out the 3 related lines brought back the action bars,

The "restore Bar" button under the Micro menu bar options fixed the location and settings as well.

**Comment by nateiorg** [comment]
If only Blizzard offered a PTR so addon developers could release immediate updates with WoW updates.

**Comment by Butain** [comment]
I had the same issue, the provided fix above for commenting out the securehook fixed it as well.

**Comment by raworre** [comment]
> 

This is the fix that worked for me. Micro menu and bag bar are still jacked up, but my other action bars are back/

**Comment by Trippadip89** [comment]
@ajamafalous 

How do you comment out on Notepad?

**Comment by ajamafalous** [comment]
> @ajamafalous
> 
> How do you comment out on Notepad?
> 
> and is line 1700 "AB:SetupMicroBar()"

Yes, it's that line. To comment something out in Lua, you just put two dashes in front of it. So the line should be:

--AB:SetupMicroBar()

**Comment by Azilroka** [comment]
![image](https://user-images.githubusercontent.com/1934853/214460374-fcd29075-af4f-42a4-adb4-5992ffa2e06f.png)

Main Branch is Release 13.21.. You guys didn't install dev correctly.

**Comment by GOOESQ** [comment]
> ![image](https://user-images.githubusercontent.com/1934853/214460374-fcd29075-af4f-42a4-adb4-5992ffa2e06f.png)
> 
> Main Branch is Release 13.21.. You guys didn't install dev correctly.

I dragged the folders over what I do wrong

**Comment by Rottentimes** [comment]
I did a // for my commenting out, seemed to work?  I did delete the securehook lines from the microbar lua file on accident, that going to screw with anything?  Or anyone have those lines for me so I can add them back in?

**Comment by jgz** [comment]
commenting in lua typically uses --

**Comment by Rottentimes** [comment]
> commenting in lua typically uses --

// only worked, I tried both.  -- made the action bars vanish again.

**Comment by kanzelm3** [comment]
> ![image](https://user-images.githubusercontent.com/1934853/214460374-fcd29075-af4f-42a4-adb4-5992ffa2e06f.png)
> 
> 
> 
> Main Branch is Release 13.21.. You guys didn't install dev correctly.

Patch 10.0.5 is live now, we shouldn't have to install dev. Can you put out a new release from main?
