### ISSUE TITLE
[Retail Bug Report] Growth X-Direction on Raid Unitframes not working properly when anchored to the left

### ISSUE THREAD

**Issue by syndenbock** [tukui-org/ElvUI#990]
### What is the issue you are having?

I have set up the debuffs of my Raid 1 Unitframes to be attached to LEFT of the frames which automatically sets the Growth X-Direction to "Right" and makes that option greyed out. However the debuffs are growing to the left, starting with the first debuff already. If I attach the debuffs to BOTTOMLEFT the Growth X-Direction is still "Right" but is no longer greyed and starts working properly. For my configuration and the displayed frames see attached screenshots.
![image](https://github.com/tukui-org/ElvUI/assets/29254285/3b0ebad8-f9e7-45f0-b85f-999130d11705)
![image](https://github.com/tukui-org/ElvUI/assets/29254285/ae0e3ce6-86d5-42e1-82c8-cd99eae42036)

### What is the expected behavior?

I expect the debuffs to properly grow to the right.

### What actually happened?

Instead of growing to the right, the debuffs are growing to the left.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
What you have described is not a bug technically.  The `Growth X-Direction` is set to be disabled when you have the `Anchor Point` set to either `Left` or `Right`, at that time, you can disregard the value in the disabled dropdown for `Growth X-Direction` because how it is coded, when set to `Left`, they will growth left. That also means, when you set the `Anchor Point` to right, it will anchor to the right and grow right. So the value displayed doesn't represent anything, so disabling that option is what we do so people dont try to adjust an option that will not physically do anything.
